name: Journeystar
favicon: null
layout_spectrum: 0.576204659184441
typography_spectrum: 0.001797363394871354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5fc01'
    - '#fbfbfb'
    - '#0c0b11'
    - '#7f7c77'
    - '#c5cace'
  brandStrength: 0.7830628519877791
  lightness: 0.6829672071617097
  saturation: 0.8163181466516107
  rhythmicContrast: 0.7088882953394204
purpose: []
